### ISSUE TITLE
incorrect rune width for box drawing characters in east asian encoding

### ISSUE THREAD

**Issue by jesseduffield** [mattn/go-runewidth#49]
When using an east asian encoding, the following runes are given a width of 2 but they should be 1: `─┌└┐┘│`.

To reproduce:
```
export LC_CTYPE="ja_JP.UTF-8"
(in go program)
runewidth.RuneWidth('─') // returns 2
```

looking at the runewidth_table.go file, the culprit is `{0x24EB, 0x254B}` in the `ambiguous` table. I'm not sure how to update this; the file is auto-generated.

In terminal apps which render box characters this can lead to broken rendering:
![image](https://user-images.githubusercontent.com/8456633/115103466-6fd36300-9f95-11eb-94c0-928f18a3e6bd.png)

Let me know if there's anything else I can add. Thanks :)

**Comment by Milly** [comment]
[Box Drawing characters (u2500 to u257f)](http://www.unicode.org/charts/PDF/U2500.pdf) has a [Ambiguous East Asian Width](http://www.unicode.org/reports/tr11-2/). It is Unicode specification.
I think the implementation of the *go-runewidth* is correct.

The solution to the problem is to configure the terminal application correctly **AND** use the correct font.

Alternatively, add an option to draw lines with only ASCII characters.

**Comment by mattn** [comment]
Could you please try
```
export RUNEWIDTH_EASTASIAN=0
```

**Comment by mattn** [comment]
Or
```go
runewidth.DefaultCondition.EastAsian = false
```

**Comment by jesseduffield** [comment]
@mattn thanks I'll give `runewidth.DefaultCondition.EastAsian = false` a go
